### ISSUE TITLE
Vivecraftの感想を書くスレ

### ISSUE THREAD

**Issue by sksat** [sksat/mc.yohane.su#156]
sksatは未プレイ(今はWindowsを起動すると鯖が死ぬため)

**Comment by lemoncmd** [comment]
IK入らんかなって無限回言ってる

**Comment by sksat** [comment]
あー

**Comment by sksat** [comment]
1.18になって動作しなくなったため一旦閉じ

**Comment by sksat** [comment]
(かなりWIPっぽいけど)こういうのもあるっぽいです
https://github.com/Sorenon/MCXR
