### ISSUE TITLE
養鶏場の軽量化(さらに収容できるようにする)

### ISSUE THREAD

**Issue by Siro256** [sksat/mc.yohane.su#158]
## 現状
[Wiki(クソデカ養鶏場)](https://github.com/sksat/mc.yohane.su/wiki/%E3%82%AF%E3%82%BD%E3%83%87%E3%82%AB%E9%A4%8A%E9%B6%8F%E5%A0%B4)の通り、養鶏場付近が非常に重く、非常に高性能なマシンでないと付近に近づくだけで操作困難に陥る。
また、養鶏場の存在するチャンクが読み込まれるとTPSが低下するのはご存じの通りだと思います。

## 解決策
[このプラグイン(ConfineChickens)](https://github.com/Siro256/ConfineChickens/)の導入を検討して頂きたいです。
効果についてはプラグインのREADMEの通り、クライアント/サーバー双方で軽量化されることが確認されています。

**Comment by sksat** [comment]
便利なプラグインもあるもんだなあと思ったら作者で草

**Comment by sksat** [comment]
mc.yohane.suに入れるプラグイン，基本的に
- ゲーム性を変えるようなものではない(なのでめちゃくちゃ掘るやつとかはちょっと微妙)
- GitHubでtagが打たれている/Releaseが出ている

を満たしていればほぼ問題無いと考えているので，なんの問題も無さそう．

**Comment by sksat** [comment]
ただまあ，鶏が衝突すると鶏が衝突しておもしろいという気もしなくはないので，それを許容するかという問題はあるかもしれない(？)

**Comment by yanorei32** [comment]
既に描画負荷の観点から養鶏場には蓋をしており、観測不能な気がしている。（どうだろうか。）

**Comment by sksat** [comment]
あの石棺についてはそうなんだけど，野晒しになってる鶏はどちらかというと衝突してほしいかもしれない(が，クソデカ養鶏場かどうかの判定をしてどうこうとかすると無意味そうだしよさそう)
