### ISSUE TITLE
インシデント20210917報告書

### ISSUE THREAD

**Issue by KisaragiEffective** [sksat/mc.yohane.su#54]
# 概要
本日午前1時47分頃、テラファーム下層部 (`567 11 -14`) 周辺で火災が発生し、昆布ブロック製の壁面約300平方ブロックが延焼した。
1時49分頃、@KisaragiEffective が発見し、消火活動に当たる。
消火後は原因究明に当たった。その結果、隣接していた洞窟の溶岩源から延焼したという結論に至った。

# 対策
* 周辺に火元、特に溶岩がないか確認する。
* 消化設備を整える。

**Comment by sksat** [comment]
火災の根本的な原因は昆布ブロックという可燃性の高いブロックを畑壁の建材として使用してしまったことであると考えられます．これに対する修正ないし対策が必要となりますが，壁を別のブロックで張り替えるといった根本的な修正は労力も必要ブロック数も大きく，現実的ではありません．

そのため，壁の昆布ブロックが延焼しやすいということの周知の徹底，そして火災発生時の消化対応オペレーションの策定といった対応が必要となります．

**Comment by sksat** [comment]
本インシデントによる壁の破壊は修復された．また，ついでに周辺の元から昆布ブロックになっていなかった部分及び周辺のマグマのチェック・湧き潰し対応なども行ったため，closeする．消化対応などについては別Issueとしたい．
