### ISSUE TITLE
大規模なチャンクロードで鯖停止 (575)

### ISSUE THREAD

**Issue by yanorei32** [sksat/mc.yohane.su#57]
## Context information
* Minecraft 1.17.1

## Reproduce the issue
* ネザーを経由しTerafarmの両端を高速移動する

## Observed result
* TPSの低下
* Heapの不足
* サーバー機能の停止

## Expected result
* TPSが落ちない
* Heapが足りている
* サーバー機能が停止しない

**Comment by sksat** [comment]
サーバ停止時のログ: https://discord.com/channels/746466726220136578/836488124582461451/889119137803153428
`java.lang.OutOfMemoryError: Java heap space`

![image](https://user-images.githubusercontent.com/23310673/133927326-4fa2d41d-42a6-48aa-a7d3-56b79e86fef0.png)

**Comment by sksat** [comment]
とりあえず再起動したのでこれは一旦close

**Comment by yanorei32** [comment]
ネザーゲート通過時overworldとnetherとの両方が一時的にロードされ、TPSが落ちこみはじめる1.5~2k chunksを超過、それが発端となり死んでいる気がする。

![image](https://user-images.githubusercontent.com/11992915/133927402-36152c82-ca4b-48a8-b59b-e8c96a189f2b.png)
