### ISSUE TITLE
restart: always が例外時に効いていない

### ISSUE THREAD

**Issue by yanorei32** [sksat/mc.yohane.su#60]
#57 発生時、Exception 等とコンソールに残しプロセスが生き残る為、 Docker による restart: always が効いていない。

悲しい。

**Comment by sksat** [comment]
かなし〜

**Comment by sksat** [comment]
maxを300MBにしてローカルでOutOfMemoryErrorを再現してみたが，やはりexitする気配なし

**Comment by sksat** [comment]
`itzg/docker-minecraft-server`では外形監視してDockerのhealthcheckに喰わせているっぽい．アイツがそうしてるんならそうするしかないんだろうな...そしてこれPaperやSpigotではなく公式の問題なんだろうな！！！！
https://github.com/itzg/docker-minecraft-server/blob/1e32161652f1549b72553deba55f9a6cbdb62d3e/Dockerfile#L89
https://github.com/itzg/docker-minecraft-server/blob/1e32161652f1549b72553deba55f9a6cbdb62d3e/health.sh

**Comment by sksat** [comment]
ということでこれは`mc.yohane.su`の設定の問題ではないため，[papermc-docker](https://github.com/sksat/papermc-docker/)で対処する．
