### ISSUE TITLE
ｷﾞｶﾞﾌｧｰﾑの照明が収穫時に剥がれる

### ISSUE THREAD

**Issue by KisaragiEffective** [sksat/mc.yohane.su#61]

**Comment by primenumber** [comment]
グロウストーンやシーランタンなど剥がれない照明を使うことが考えられます

**Comment by sksat** [comment]
これって現状どんなかんじなんですかね cc: @KisaragiEffective @yanorei32 @hsjoihs @primenumber

**Comment by yanorei32** [comment]
運用でカバーされている。

**Comment by KisaragiEffective** [comment]
改善工事の兆しは見られるものの、遅々として進まない。

**Comment by sksat** [comment]
OK．ということでアサインしました

**Comment by yanorei32** [comment]
done

![2021-10-31_19 15 05](https://user-images.githubusercontent.com/11992915/139577880-13657a60-dde2-436a-b4e1-8fcfe914275e.png)

**Comment by sksat** [comment]
:erait:
