### ISSUE TITLE
特定領域で任意の「ブロック」に対するユーザー操作が正常に動作しない

### ISSUE THREAD

**Issue by yanorei32** [sksat/mc.yohane.su#78]
SSIA.
チャンクではない謎の領域単位で発生している。

## Context information
* Minecraft 1.17.1

## Reproduce the issue
* 特定領域 (SPAWNチャンク周辺) に行く

## Observed result
特定領域内で
* 寝られない
* エンダーチェスト/作業台/樽/チェスト/ホッパー/燻製器/溶鉱炉/鍛冶台/製図台/金床が開かない
  * チェスト付きトロッコは開く
* ブロックが不死身/設置不能
* 各種鉄の扉がボタンにより正常に開かない
* トラップドア/ドアがクリックで開閉不能 (ドアは感圧板で開閉可能)

## Expected result
* 怪奇現象が止まる

REF:
https://twitter.com/yanorei32/status/1440984240691109888?s=20
https://youtu.be/EP79KlrVBj4

**Comment by yanorei32** [comment]
```
[-30], 71, -31: OK
[-31], 71, -31: NG
[-63], 62, -36: NG
[-64], 62, -36: OK

-33, 70, [-19]: OK
-33, 70, [-20]: NG
-45, 62, [-52]: NG
-45, 62, [-53]: OK
```

**Comment by Ry0taK** [comment]
server.propertiesの`spawn-protection=16`を変えれば治る気がする

**Comment by yanorei32** [comment]
今まで問題が発生しなかった事及び、チェスト・扉が開かないのは不思議な気がします。

**Comment by sksat** [comment]
spawn protection is 何？

**Comment by sksat** [comment]
https://minecraft.fandom.com/ja/wiki/Server.properties
> スポーン保護の半径を2x+1として決定する。これを0に設定しても、スポーン保護は無効にならない。0は、スポーンポイントの単一ブロックを保護する。1は、スポーンポイントを中心とした3x3の領域を保護する。2は5x5を保護し、3は7x7を保護する。このオプションは、最初のサーバーの起動時に生成されず、最初のプレーヤーが参加したときに表示される。 サーバーにopsが設定されていない場合、スポーン保護は自動的に無効になる。 

とあるので，スポーン保護なる概念がopsを設定したことにより発動したのは普通にありそう

**Comment by sksat** [comment]
スポーン保護，まんまこういう挙動をするものっぽい(マルチ用の設定とのこと)

**Comment by sksat** [comment]
完全に無効化はできないのか

**Comment by sksat** [comment]
プルリクとリンクさせたいがそれはそれとしてマージされたからってIssue閉じないでほしい，みたいな気持ちがややある

**Comment by sksat** [comment]
デプロイされたんで`server.properties`適用いきます

**Comment by sksat** [comment]
@yanorei32 修正されたと思うんで確認お願いします

**Comment by yanorei32** [comment]
直ってます。完全にこれでした。
