### ISSUE TITLE
ログをいいかんじに保存 or 見たい

### ISSUE THREAD

**Issue by sksat** [sksat/mc.yohane.su#87]

**Comment by Ry0taK** [comment]
DiscordSRVの[`DiscordConsoleChannelId`](https://github.com/DiscordSRV/DiscordSRV/blob/1d08598206b1af5dcc29eDiscordConsoleChannelId11cead8e152e4c3f94/src/main/resources/config/en.yml#L31-L32)を設定すると良いかもしれません

**Comment by sksat** [comment]
有用情報だ

**Comment by sksat** [comment]
https://github.com/DiscordSRV/DiscordSRV/blob/1d08598206b1af5dcc29e411cead8e152e4c3f94/src/main/resources/config/ja.yml#L180
> DiscordConsoleChannelBlacklistActsAsWhitelist: "DiscordConsoleChannelBlacklistedCommands"設定を、ブラックリストの代わりにホワイトリストとして動作させるかどうか

そう，か？

**Comment by sksat** [comment]
あーこれ`config.yml`にDiscord bot tokenとか入れないといけないの最悪だな．Git管理できない．

**Comment by sksat** [comment]
とりあえずこれでいいか
