### ISSUE TITLE
アイテム数カウントグラフでの鉄の合計量がおかしい

### ISSUE THREAD

**Issue by kory33** [sksat/mc.yohane.su#98]
インゴットを9倍してそう
![image](https://user-images.githubusercontent.com/6561358/134777931-032c0bcc-a031-48a4-b5b9-c5dceafa334a.png)

**Comment by sksat** [comment]
あ，説ある

**Comment by sksat** [comment]
そうでした

**Comment by sksat** [comment]
fixed
