### ISSUE TITLE
拠点内に敵モブがスポーンする

### ISSUE THREAD

**Issue by primenumber** [sksat/mc.yohane.su#99]
- 周囲の洞窟を湧き潰したため、スポーンしやすい
- 外からドア無しで進入可能
- 外の湧きつぶしは不十分
- そもそも拠点内も完全に湧きつぶしされているか怪しい

**Comment by sksat** [comment]
人々が湧き潰しを頑張っていそう

**Comment by primenumber** [comment]
拠点をすべてモブが湧かないブロックで構成しよう

**Comment by lemoncmd** [comment]
見落としがなければ地上の湧きつぶしは完了（見つけ次第湧きつぶしただけと同義）
海底もわきつぶせるとヨロシアル

**Comment by sksat** [comment]
これって現状どうなんでしょ，と思ったが実は完了しとる？

**Comment by sksat** [comment]
してそうなのでclose．海底はやりたくなるか必要が生じたらでいいでしょう．
